### ISSUE TITLE
Table 생성

### ISSUE THREAD

**Issue by harudev** [ruci06/vote_widget#1]
Movie Table
id : pk
title : 영화명, varchar
director_name : 감독명, varchar
summary : 줄거리, text
premier : 개봉일, date
genre : 장르, varchar
country : 국가, varchar
vote_count : 투표수

영화가 너무 많아질 경우에 sorting, 조건부 쿼리를 제공하기 위한 필드들 추가
투표수가 많아질 경우 일일이 투표내역을 카운팅 하는데에 부하가 크므로 투표시에 투표수를 추가/수정

**Comment by ruci06** [comment]
추가 필드가 있으면 안될 것인가?
ex) 클라이언트 access token, active 등

**Comment by harudev** [comment]
User Table
id : pk
name : 사용자명
movie_id : foreign key

**Comment by harudev** [comment]
api client table 추가
